# 1. Create a null vector of size 10 but the fifth value which is 1.

In [2]:
import numpy as np
array=np.zeros(10)
array[4]=1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 2. Create a vector with values ranging from 10 to 49.

In [4]:
array_1=np.arange(10,50)
print(array_1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 3. Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
array_2=np.arange(9).reshape(3,3)
print(array_2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [7]:
non_zero=np.nonzero([1,2,0,0,4,0])
print(non_zero)

(array([0, 1, 4], dtype=int64),)


# 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [14]:
array_3=np.random.random((10,10))
array_3_min,array_3_max=array_3.min(),array_3.max()
print(array_3_min,array_3_max)

0.020065807203523578 0.9943355485147317


# 6. Create a random vector of size 30 and find the mean value.

In [16]:
array_4=np.random.random(30)
mean_val=array_4.mean()
print(mean_val)

0.41994714286736895
